# Generated by Django 4.1.2 on 2022-10-25 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='profiel',
            new_name='profile',
        ),
    ]
